version: "2.4"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_started
